[package]
name = "sphere_native"
version = "0.1.0"
edition = "2024"

[lib]
name = "sphere_native_rust"
crate-type = ["cdylib"]
[dependencies]

pyo3 = { version = "0.21", features = ["extension-module"] }
